lang: ruby
before_install: gem install bundler --pre
install:
  - gem update --system
  - bundle update
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
notifications:
  recipients:
    - namusyaka@gmail.com
branches:
  only:
    - master
